### ISSUE TITLE
A file may have no metadata

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#103]
Something that could happen is a mp3 files without any metadata. Have to get that working too.

```
VM332:2 Uncaught Error: Could not find metadata header
```

===

### Todo

Basically, the goal is to make `utils.getMetadata` agnostic, whatever is the file sent to it, so we are sure to get nicely formatted metadata and duration

- [x] Get rid of mime in `utils.js` ?
- [ ] Create a `getDefaultMetadata` method in `utils.js` that is called when an error is thrown
- [ ] This method should return basically that:
``` javascript
// track is a file path
return {
    album        : 'Unknown',
    albumartist  : [],
    artist       : ['Unknown artist'],
    disk         : {
        no: 0,
        of: 0
    },
    duration     : duration, // must be computed somewhere
    genre        : [],
    loweredMetas : {},
    path         : track.path,
    playCount    : 0,
    title        : path.parse(track.path).base,
    track        : {
        no: 0,
        of: 0
    },
    type         : 'track',
    year         : ''
};
```
- [x] Call `getDefaultMetadata` directly for wav files
- [x] If musicmetadata does not return any duration, we should get it with something like (need perfs test). The problem is it's really slow.
``` javascript
const audio = new Audio();
audio.src = track.path;
audio.addEventListener('load', () => {
    // audio.duration
});
```
- [x] Maybe get rid of `wav-file-info` in that case

**Comment by YurySolovyov** [comment]
Can you upload this file somewhere?
Is this issue about current metadata parsers not being able to get data from some files, or in general, where metadata is wiped out on purpose, or both?

**Comment by KeitIG** [comment]
It seems it happens when there is no metadata header. The problem is just there should be a try/catch comparing returned errors. Another problem is when this happens, duration is not provided too.

So this is a mix of fixes and a bit of what I've done with wav files when there is no metadata.

**Comment by KeitIG** [comment]
Task list updated.

**Comment by YurySolovyov** [comment]
Note to self: might want to use https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API#Audio_Workers or some kind of background processing for the worst case.

**Comment by YurySolovyov** [comment]
One more note: we might not wait for entire file to load and use 
[`loadedmetadata`](https://developer.mozilla.org/en-US/docs/Web/Events/loadedmetadata) event instead.

**Comment by KeitIG** [comment]
Yes, it's indeed much faster (20ms vs 500ms)
