### ISSUE TITLE
Create builds for each platform

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#48]
Ideally, at each release, 3 apps should be built:

- .exe (installer xor not)
- .app 
- .deb

Here are some tools: 
https://github.com/maxogden/electron-packager
https://www.npmjs.com/package/electron-builder

And a related issue on Electron https://github.com/atom/electron/issues/673

Here are how the build "should" be. All of this can be done in a script, preferably in JavaScript rather than in bash or something.

### TODO
- [x] Start the script ?
- [x] Check if the `ignore` parameter works
- [x] Remove sources and add compiled files and assets

**Comment by KeitIG** [comment]
now what I'm looking for, but this could be a first step

https://www.npmjs.com/package/electron-builder

**Comment by Phenitei** [comment]
I'll help with the GNU/Linux builds ;-)

**Comment by Phenitei** [comment]
After packaging to a .app using electron-packager, running on my (2008) macbook with OS X Yosemite yeilds the attached errors. Missing dependencies? If yes, which are they
![screen shot 2015-12-27 at 12 45 16 am](https://cloud.githubusercontent.com/assets/16446460/12008329/251cca8a-ac35-11e5-9549-59f297b45696.png)
? (I can then find out how to add them)

**Comment by Phenitei** [comment]
After packaging to a .app using electron-packager, running on my (2008) macbook with OS X Yosemite yeilds the attached errors. Missing dependencies? If yes, which are they
? (I can then find out how to add them)
![screen shot 2015-12-27 at 12 45 16 am](https://cloud.githubusercontent.com/assets/16446460/12008356/2e0853b6-ac36-11e5-83cd-8a7077763a84.png)

**Comment by KeitIG** [comment]
ooooh I think I know why, this errors is sent by `main.js`: `teeny-conf` is the only package use in `main.js`, and as `node_modules` is not in the app, electron can't find it.

That's an interesting case, I should take a look at `electron-packager` issues/doc

**Comment by Phenitei** [comment]
The electron packager documentation states that 
```
Be careful not to include node_modules you don't want into your final app. electron-packager, electron-prebuilt and .git will be ignored by default. You can use --ignore to ignore files and folders via a regular expression. For example, --ignore=node_modules/electron-packager or --ignore="node_modules/(electron-packager|electron-prebuilt)"
```
From what I understand that means that the ```node_modules``` are included in the .app (which would also explain it's size)...

**Comment by KeitIG** [comment]
so you would just need  something like `--ignore="node_modules/(electron-packager|electron-prebuilt|teeny-conf)"`

**Comment by KeitIG** [comment]
so you would just need a regex that ignore everrything except `teeny-conf`

**Comment by Phenitei** [comment]
You sure don't need any others?

**Comment by KeitIG** [comment]
The only modules we need in `main.js` are 

``` javascript
var path     = require('path'),
    teeny    = require('teeny-conf'),
    electron = require('electron');
```

`electron` and `path` are included in Electron

**Comment by Phenitei** [comment]
Ok. That still doesn't explain why it failed to be packaged with the
.app the first time though as I did not pass the ```--ignore``` option,
so all modules should have been packaged in...

**Comment by KeitIG** [comment]
Things left to do: 
- Check if the `ignore` parameter works
- Remove sources and add compiled files and assets

**Comment by KeitIG** [comment]
Closing it. I'll open a new issue for installers.
